"""Añadir tabla Producto

Revision ID: e6a03930d14a
Revises: 8ea55430be9e
Create Date: 2024-07-27 00:38:47.515271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6a03930d14a'
down_revision = '8ea55430be9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grado', sa.String(length=100), nullable=False),
    sa.Column('seccion', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aula')
    # ### end Alembic commands ###
